/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package robtest;

import com.google.inject.Guice;
import com.google.inject.Injector;
import robtest.stateinterfw.IStarter;
import robtest.stateinterfw.guice.*;

public class App {
    public static void main(String[] args) {
        Injector injector = Guice.createInjector(
                new MapperModule(),
                new DatabaseModule(),
                new FrameworkModule(),
                new EnvironmentModule(),
                new FaultModule()
        );
        IStarter starter = injector.getInstance(IStarter.class);
        starter.start();
    }
}
