/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package robtest;

import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import robtest.stateinterfw.hbm.*;

import java.util.Date;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        ISqlManager sqlManager = new SqlManager();
        sqlManager.createSession(session -> {
            TestCase testCase = new TestCase();
            MutantTestCase mutantTestCase = new MutantTestCase(testCase);
            session.save(testCase);
            session.save(mutantTestCase);
            return true;
        });
    }
}
