/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wafec.testing.driver.openstack.client;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.openfeign.EnableFeignClients;

@SpringBootApplication
@EnableFeignClients
public class App implements CommandLineRunner {
    @Autowired
    private FlavorClient flavorClient;

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

    @Override
    public void run(String... args) throws Exception {
        System.out.println("Working...");
        /*var flavorCreateResult = flavorClient.create("1", Flavor.of("test123", 300, 1, 1));
        System.out.println(flavorCreateResult.toString());*/
        for (var flavor : flavorClient.getAll("1")) {
            System.out.println(flavor.toString());
        }
    }
}
