/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wafec.testing.driver.openstack.client;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

}
